# https://learnxinyminutes.com/docs/yaml/

theme: minima
github_username: vinc456

# defaults as described by https://help.github.com/articles/configuring-jekyll/
github: [metadata]
 encoding: UTF-8
 kramdown:
   input: GFM
   hard_wrap: false
 future: true
 jailed: false
 theme: jekyll-theme-primer
 gfm_quirks: paragraph_end